### PR TITLE
Core Engineering Proposals

### PR DESCRIPTION
**Pull request by OwenArnold**
Will be reviewed at the ESS and then by the wider TSC/Mantid team before making its way to repository mantidproject/documents

### CODE REVIEW

**Comment by OwenArnold** [comment]
@SimonHeybrock We need to add something on our Concept work.  Once we have this in a good state, we should discuss with @Jon-Taylor

**Comment by SimonHeybrock** [comment]
Notes for myself (will edit the document later):

- Flexible library for working with histograms (extending current `HistogramData`, which is currently very basic and has no Python exports yet).
- Library for working with neutron events at the level of `EventList` and below. Possibly also for internals of `MDEventWorkspace`?
- Library for working with crystallography-related concepts, such as HKL values, point- and space-groups (based on work by Michael)
- Library for working with log files (or rather log entries)
- Library for fitting (w/o workspaces)
- New and better workspace types (not just reducing messy use of `MatrixWorkspace`, but work towards a complete replacement, since `MatrixWorkspace` is very hard to understand)
- Libraries for other basic (neutron-)physics related concepts (unit conversion, ...?)

**Comment by SimonHeybrock** [comment]
@OwenArnold I added some section, very brief and incomplete. I do not know to what level you want to describe them. The sections on motivation and risks could usually contain most of what we wrote in the proposal, but there is not point in copying this everywhere, I guess.

**Comment by OwenArnold** [comment]
Thanks @SimonHeybrock I think the next steps here would be to discuss with Jon.

**Comment by OwenArnold** [comment]
I'm going to merge this in the state that @SimonHeybrock  and myself agree. We can consider amendments as required.

**Pull request merged**
